import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from '../app/components/header/header.js'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//aquela pagina do react que tinha pra fazer router

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Header/>
      <main className="p-6">{children}</main>
        {/* //footer */}
      </body>
    </html>
  );
}
